### ISSUE TITLE
Reexaminar las licencias

### ISSUE THREAD

**Issue by JJ** [Sipesca/Datasets#1]
GPL es más bien para programas. Para datos existen las [Open Data Licenses](http://opendatacommons.org/licenses/) Yo aconsejaría la Open Database License, pero en todo caso mirarlas y decidir cuál de ellas puede ser las más adecuada.

**Comment by deantares** [comment]
Okis, gracias! 

De hecho te tenía pensado preguntar o a @psicobyte por este tema que se que controláis. 

Un saludote

**Comment by pacastillo** [comment]
¡Gracias, JJ!
Luego miro las diferencias para ver cuál nos puede venir mejor.
